---
- name: Get Crumb From Jenkins
 win_uri:
   url: http://{{ host_name }}:8080/crumbIssuer/api/json
   force_basic_auth: "yes"
   user: "{{ user }}"
   password: "{{ password }}"
   method: get
   return_content: "yes"
 register: result
 tags:
   - always

- set_fact:
    content: "{{ result | json_query('content') }}"

- set_fact:
    crumb: "{{ content.crumb }}"
 
- debug:
    msg: "Crumb Retrieved: {{ crumb }}"

# curl command intiated
#java -jar jenkins-cli.jar -s http://{{ host_name }}:8080/ -auth admin:password create-job 'VMs_missing_BusinessOwner' < VMs_missing_BusinessOwner.xml 
