---

# Values to be used when performing a default Oracle installation
db_sid: A001

db_user: system
db_pass: ///
db_sysdba_user: sys
db_sysdba_pass: ///

oracle_username: oracle
oracle_password: ///

linux_tmp_dir: '/tmp/devops'

oracle_database_groups:
  - oinstall
  - dba
  - oper

OSDBA_GROUP: dba
oracle_config_script: oracle_create_db_script.sql
oracle_user_script: oracle_create_user_oseries_script.sql
ORACLE_INVENTORY: /u01/app/oracle/oraInventory
InstallEdition: EE
UNIX_GROUP_NAME: oinstall
ORACLE_BASE: /u01/app/oracle
storageType: FILE_SYSTEM_STORAGE
dataLocation: /u01/app/oracle/oradata/{{ db_sid }}
oracle_install_rsp: 'oracle{{ oracle_version }}_advanced_install.rsp'
characterSet: AL32UTF8
