---

- name: "Download bulkloader"
  win_get_url:
    url: "{{ vertex_bulkloader_url }}/bulkloader.zip"
    dest: "{{ oseries_home }}/dataupdate"
    force: no

- name: "Unzip bulkloader Package."
  win_unzip:
    src: "{{ oseries_home }}/dataupdate/bulkloader.zip"
    dest: "{{ oseries_home }}/dataupdate"
#    delete_archive: yes

