---
- name: "Checking for O Series Patch - Windows"
  win_stat:
    path: C:\vertex\oseries\patch\vertex_root\config
  register: oseries_patch_win

- name: "Copying O Series patch to local system"
  win_get_url:
      url: "{{oseries9_repo_url }}/{{ path_to_patch }}/{{ o_series_patch }}"
      dest: "{{ oseries_home }}\\patch"
  when: not oseries_patch_win.stat.exists

- name: "Installing O Series patch"
  win_shell: 'java -jar {{ oseries_home }}/patch/{{ o_series_patch }}'
  when: not oseries_patch_win.stat.exists
