---
wildfly_repo_base_dir: https://binrepo.vtxdev.net/artifactory/software-local/AppServers/wildfly/
wildfly_package: wildfly-17.0.0.Final.zip
wildfly_install_base: C:\DeploymentUnit
wildfly_dir: wildfly-17.0.0.Final
wildfly_oseries_war_dir: C:\vertex\oseries\web
wildfly_custom_config: standalone.xml

