---
# Ansible Playbook to validate the O Series directories

- name: "Checking for user {{ item.name }}"
  shell: |
    exec > {{vertex_tmp_dir}}/{{ vertex_artifact_file }} 2>&1
    id {{ item.name }}
    grep {{ item.name }} /etc/passwd
    echo ""
  register: user_exists
  with_items:
    - "{{ oseries_users }}"

- name: "Validating O Series directories"
  shell: "ls -ld {{ item }} >> {{vertex_tmp_dir}}/{{ vertex_artifact_file }}"
#  ignore_errors: true
    
  with_items:
  - "{{ oseries_directories }}"
