# Ansible Playbook to subscribe to RedHat

- name: Check if the RHEL server is already registered to recieve updates
  stat:
    path: '{{ rhel_repos }}/redhat.repo.bak'
  register: stat_result
    
- name: Installing katello-satellite repo
  shell: 'yum localinstall http://phlpsatellite1.vertexinc.com/pub/katello-ca-consumer-latest.noarch.rpm -y'
  args:
    warn: no
  become: true
  when: not stat_result.stat.exists

- name: Registering to satellite
  shell: 'subscription-manager register --org="vertex-inc" --activationkey="RHEL{{ hostvars[inventory_hostname].ansible_distribution_major_version }}-Standard-operating-environment"'
  become: true
  register: register_result
  failed_when: "'FAILED' in register_result.stderr"
  when: not stat_result.stat.exists


- name: Attaching subscription manager
  shell: 'subscription-manager attach --auto'
  become: true
  when: not stat_result.stat.exists

- name: Listing repos
  shell: 'subscription-manager repos --list'
  become: true
  when: not stat_result.stat.exists

- name: Installing katello agent
  shell: 'yum install katello-agent -y'
  become: true
  when: not stat_result.stat.exists
  
- name: Installing RHEL {{ hostvars[inventory_hostname].ansible_distribution_major_version }} Updates
  shell: 'yum update -y'
  args:
    warn: no
  become: true
  when: not stat_result.stat.exists

- name: Created redhat.repo backup
  shell: mv '{{ rhel_repos }}/redhat.repo' '{{ rhel_repos }}/redhat.repo.bak'
  when: not stat_result.stat.exists
