---
- name: "Creating Vertex Scripts Directory"
  win_file:
    path: "{{ vertex_tmp_dir }}"
    state: "{{ vertex_dir_state }}"

- name: "Creating Vertex Temp Directory"
  win_file:
    path: "{{ vertex_scripts_dir }}"
    state: "{{ vertex_dir_state }}"
  
- name: "Copy ListOrgTeamMembers.ps1"
  win_copy:
    src: "files/ListOrgTeamMembers.ps1"
    dest: "{{ vertex_scripts_dir }}"

- name: "Copy parameters.json"
  win_copy:
    src: "files/parameters.json"
    dest: "{{ vertex_scripts_dir}}"

- name: "Copy vra_compare.py"
  win_copy:
    src: "files/vra_compare.py"
    dest: "{{ vertex_scripts_dir}}"

- name: "Download PowerShell"
  win_get_url:
    url: "{{ vertex_repo_url }}/{{ powershell_pkg }}"
    dest: "{{ vertex_tmp_dir }}/"
    force: no

- name: "Install POWERSHELL 7.x CORE from msi"
  win_package:
    path: "{{ vertex_tmp_dir }}\\{{ powershell_pkg }}"
    state: present

- name: "Set Security Protocol to Tls12 and NuGet Provider"
  win_shell: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force"

- name: "Register Repository"
  win_shell: "Register-PSRepository -Default -Verbose"

- name: "Tls12 and Force Vmware Install"
  win_shell: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Install-Module -Name VMware.PowerCLI -Force -AllowClobber -SkipPublisherCheck"

#- name: "Install vmware Powershell Module"
#  win_psmodule:
#    name: Vmware.PowerCLI
#    state: present
  
- name: Install RSAT-AD Features
  win_feature:
    name: RSAT-AD-PowerShell
    state: present

- name: "Add Active Directory powershell module"
  win_psmodule:
    name: ActiveDirectory
    state: present

- name: Install AD Features
  win_feature:
    name: AD-Domain-Services
    state: present

- name: "Installing Packages"
  win_chocolatey:
    name: "{{ item.name }}"
    state: "{{ pkg_state }}"
    version: "{{ item.version }}"
    ignore_checksums: yes
  with_items:
    - "{{ util_pkgs }}"
