---

# ==> Set facts for Artifactory location
- name: Overridding of vars from common
  set_fact:
    db_version: Oracle
    vertex_repo_url: 'http://binrepo.cst.vertexinc.com:80/artifactory/software-remote'
    key_value: "" # this line is simply a workaround to mute an error msg. See https://github.com/VSChina/vscode-ansible/issues/261

# ==> Set facts for Oracle 12.2 version
- name: Setting Hana database Facts
  set_fact:
    hana_repo_base_dir: SAP_HANA/2.0%20Express%20Installer
    hana_install_pkg: hxe.tgz
    hana_user: system
    hana_passwd: ///
    hana_oseries_user: system
    hana_oseries_passwd: ///
    hana_create_file: HANA_Create_OSeries_DB.sql
    hana_config_file: HANA_Config_OSeries_DB.sql
    hana_response_file: install.rsp
    hana_response_xml: install.rsp.xml
    hana_home_dir: /opt/media
  when: db_type == 'hana'
