---

  - name: Install the latest version of python3-psycopg2
    yum:
      name: python3-psycopg2
      state: latest
    when: db_type == "pgsql" and {{ hostvars[inventory_hostname].ansible_distribution_major_version }} == 8 

  - name: Install the latest version of python3-psycopg2
    yum:
      name: python-psycopg2
      state: latest
    when: db_type == "pgsql" and {{ hostvars[inventory_hostname].ansible_distribution_major_version }} == 7
    
  - name: Kill all active sessions of {{ db_name }} database
    postgresql_query:
      db: postgres
      login_user: "{{ pg_db_admin }}"
      login_password: "{{ pg_db_admin_pass }}"
      query: select pg_terminate_backend(pid) from pg_stat_activity where datname='oseries' and pid <> pg_backend_pid();

  - name: Dropping {{ db_name }} database   
    postgresql_db:
      login_user: "{{ pg_db_admin }}"
      login_password: "{{ pg_db_admin_pass }}"
      name: "{{ db_name }}"
      state: absent

  - name: Dropping {{ pg_db_user }} user
    postgresql_user:
      login_user: "{{ pg_db_admin }}"
      login_password: "{{ pg_db_admin_pass }}"
      db: postgres
      priv: ALL
      name: "{{ pg_db_user }}"
      state: absent
      fail_on_user: no

  - name: Creating {{ pg_db_user }} user
    postgresql_user:
      login_user: "{{ pg_db_admin }}"
      login_password: "{{ pg_db_admin_pass }}"
      name: "{{ pg_db_user }}"
      password: "{{ pg_db_user_pass }}"
      state: present
      role_attr_flags: CREATEROLE,CREATEDB,SUPERUSER

  - name: Creating {{ db_name }} database
    postgresql_db:
      login_user: "{{ pg_db_user }}"
      login_password: "{{ pg_db_user_pass }}"
      name: "{{ db_name }}"
      state: present
      owner: "{{ pg_db_user }}"

  - name: Restoring {{ db_name }} database
    postgresql_db:
      login_user: "{{ pg_db_admin }}"
      login_password: "{{ pg_db_admin_pass }}"
      name: "{{ db_name }}"
      state: restore
      target: "/mnt/backups/{{ backup_file_name }}.dump"
