---
# The version of Postgres will be passed externally
# Possible version numbers are 9,10,11,12,13

db_postgres_user: postgres
db_postgres_pass: ///
postgres_home_username: PostgreSQL
PREFIX: 'C:\DeploymentUnit\{{ postgres_home_username }}\{{pgsql_version}}'
PGDATA: 'E:\{{ postgres_home_username }}\{{ pgsql_version }}\data'
