---
    #pgsql_version: 10
    #pgsql_pkg_version: 10.7
    pgsql_user: postgres
    pgsql_pass: $1$P4I/7hd0$LauEZlEwGh5JnPBNqi2gV1
    pgsql_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36333162393935313764373539343738633461663939323134323532323738613733383664373135
          6166336130393865323038303035376463383238316535330a366432346563636439396166663734
          65613236613336376537613039353530346464303665373463363166313535343136613266393763
          3035353334336566300a346430363234346130303966366334616234353136326238666130306630
          6564
    pgsql_dirs:
      - /u01/PGDATA/A001/amountBilledToDate
      - /u01/PGDATA/A001/adminOriginTaxAreaId
      - /u01/PGDATA/A001/adminOriginSubDivision
      - /u01/PGDATA/A001/adminOriginStreet2
      - /u01/PGDATA/A001/adminOriginStreet
      - /u01/PGDATA/A001/adminOriginPostalCode
      - /u01/PGDATA/A001/adminOriginMainDivision
      - /u01/PGDATA/A001/adminOriginLocationCode
      - /u01/PGDATA/A001/adminOriginLocCustStatus
      - /u01/PGDATA/A001/adminOriginCurrConversion
      - /u01/PGDATA/A001/adminOriginCurrUnit
      - /u01/PGDATA/A001/adminOriginCountry
      - /u01/PGDATA/A001/adminOriginCity
      - /u01/PGDATA/A001/adminDestinationTaxAreaId
      - /u01/PGDATA/A001/adminDestinationSubDivision
      - /u01/PGDATA/A001/adminDestinationStreet2
      - /u01/PGDATA/A001/adminDestinationStreet
      - /u01/PGDATA/A001/adminDestinationPostalCode
      - /u01/PGDATA/A001/adminDestinationMainDivision
      - /u01/PGDATA/A001/adminDestinationLocationCode
      - /u01/PGDATA/A001/adminDestinationLocCustStatus
      - /u01/PGDATA/A001/adminDestinationCurrConversion
      - /u01/PGDATA/A001/adminDestinationCurrUnit
      - /u01/PGDATA/A001/adminDestinationCountry
      - /u01/PGDATA/A001/adminDestinationCity
      - /u01/PGDATA/A001/buyerRegistrationNumber
      - /u01/PGDATA/A001/buyerRegMainDivision
      - /u01/PGDATA/A001/buyerRegistrationCountry
      - /u01/PGDATA/A001/buyerPhysicalPresenceInd
      - /u01/PGDATA/A001/batchId
      - /u01/PGDATA/A001/combinedRate
      - /u01/PGDATA/A001/customerBusinessInd
      - /u01/PGDATA/A001/customerRegistrationNumber
      - /u01/PGDATA/A001/customerRegMainDivision
      - /u01/PGDATA/A001/customerRegistrationCountry
      - /u01/PGDATA/A001/customerPhysicalPresenceInd
      - /u01/PGDATA/A001/customerName
      - /u01/PGDATA/A001/customerCode
      - /u01/PGDATA/A001/customerClass
      - /u01/PGDATA/A001/currencyCode
      - /u01/PGDATA/A001/countryOfOrigin
      - /u01/PGDATA/A001/costCenter
      - /u01/PGDATA/A001/cost
      - /u01/PGDATA/A001/companyCode
      - /u01/PGDATA/A001/chargedTax
      - /u01/PGDATA/A001/chainTransactionPhase
      - /u01/PGDATA/A001/calcBothInd
      - /u01/PGDATA/A001/documentNumber
      - /u01/PGDATA/A001/documentDate
      - /u01/PGDATA/A001/divisionCode
      - /u01/PGDATA/A001/destinationTaxAreaId
      - /u01/PGDATA/A001/destinationSubDivision
      - /u01/PGDATA/A001/destinationStreet2
      - /u01/PGDATA/A001/destinationStreet
      - /u01/PGDATA/A001/destinationPostalCode
      - /u01/PGDATA/A001/destinationMainDivision
      - /u01/PGDATA/A001/destinationLocationCode
      - /u01/PGDATA/A001/destinationLocCustStatus
      - /u01/PGDATA/A001/destinationCurrConversion
      - /u01/PGDATA/A001/destinationCurrUnit
      - /u01/PGDATA/A001/destinationCountry
      - /u01/PGDATA/A001/destinationCity
      - /u01/PGDATA/A001/departmentCode
      - /u01/PGDATA/A001/deliveryTerm
      - /u01/PGDATA/A001/errorText
      - /u01/PGDATA/A001/extendedPrice
      - /u01/PGDATA/A001/exportId
      - /u01/PGDATA/A001/freight
      - /u01/PGDATA/A001/flexibleNumericField10
      - /u01/PGDATA/A001/flexibleNumericField9
      - /u01/PGDATA/A001/flexibleNumericField8
      - /u01/PGDATA/A001/flexibleNumericField7
      - /u01/PGDATA/A001/flexibleNumericField6
      - /u01/PGDATA/A001/flexibleNumericField5
      - /u01/PGDATA/A001/flexibleNumericField4
      - /u01/PGDATA/A001/flexibleNumericField3
      - /u01/PGDATA/A001/flexibleNumericField2
      - /u01/PGDATA/A001/flexibleNumericField1
      - /u01/PGDATA/A001/flexibleDateField5
      - /u01/PGDATA/A001/flexibleDateField4
      - /u01/PGDATA/A001/flexibleDateField3
      - /u01/PGDATA/A001/flexibleDateField2
      - /u01/PGDATA/A001/flexibleDateField1
      - /u01/PGDATA/A001/flexibleCodeField25
      - /u01/PGDATA/A001/flexibleCodeField24
      - /u01/PGDATA/A001/flexibleCodeField23
      - /u01/PGDATA/A001/flexibleCodeField22
      - /u01/PGDATA/A001/flexibleCodeField21
      - /u01/PGDATA/A001/flexibleCodeField20
      - /u01/PGDATA/A001/flexibleCodeField19
      - /u01/PGDATA/A001/flexibleCodeField18
      - /u01/PGDATA/A001/flexibleCodeField17
      - /u01/PGDATA/A001/flexibleCodeField16
      - /u01/PGDATA/A001/flexibleCodeField15
      - /u01/PGDATA/A001/flexibleCodeField14
      - /u01/PGDATA/A001/flexibleCodeField13
      - /u01/PGDATA/A001/flexibleCodeField12
      - /u01/PGDATA/A001/flexibleCodeField11
      - /u01/PGDATA/A001/flexibleCodeField10
      - /u01/PGDATA/A001/flexibleCodeField9
      - /u01/PGDATA/A001/flexibleCodeField8
      - /u01/PGDATA/A001/flexibleCodeField7
      - /u01/PGDATA/A001/flexibleCodeField6
      - /u01/PGDATA/A001/flexibleCodeField5
      - /u01/PGDATA/A001/flexibleCodeField4
      - /u01/PGDATA/A001/flexibleCodeField3
      - /u01/PGDATA/A001/flexibleCodeField2
      - /u01/PGDATA/A001/flexibleCodeField1
      - /u01/PGDATA/A001/fairRentalValue
      - /u01/PGDATA/A001/fairMarketValue
      - /u01/PGDATA/A001/generalLedgerAccount
      - /u01/PGDATA/A001/intrastatCommodityCode
      - /u01/PGDATA/A001/inputTotalTax
      - /u01/PGDATA/A001/locationCode
      - /u01/PGDATA/A001/lineItemNumber
      - /u01/PGDATA/A001/lineItemDiscountPercentage
      - /u01/PGDATA/A001/lineItemDiscountCategoryCode
      - /u01/PGDATA/A001/lineItemDiscountAmount
      - /u01/PGDATA/A001/landedCost
      - /u01/PGDATA/A001/modeOfTransport
      - /u01/PGDATA/A001/messageType
      - /u01/PGDATA/A001/materialCode
      - /u01/PGDATA/A001/netMassKilograms
      - /u01/PGDATA/A001/netBookValue
      - /u01/PGDATA/A001/natureOfTransaction
      - /u01/PGDATA/A001/ownerRegMainDivision
      - /u01/PGDATA/A001/ownerRegNumber
      - /u01/PGDATA/A001/ownerRegCountry
      - /u01/PGDATA/A001/ownerPhysicalPresenceInd
      - /u01/PGDATA/A001/originalCurrencyCode
      - /u01/PGDATA/A001/purchaseCode
      - /u01/PGDATA/A001/purchaseClassCode
      - /u01/PGDATA/A001/projectNumber
      - /u01/PGDATA/A001/productCode
      - /u01/PGDATA/A001/productClassCode
      - /u01/PGDATA/A001/postingDate
      - /u01/PGDATA/A001/physicalOriginTaxAreaId
      - /u01/PGDATA/A001/physicalOriginSubDivision
      - /u01/PGDATA/A001/physicalOriginStreet2
      - /u01/PGDATA/A001/physicalOriginStreet
      - /u01/PGDATA/A001/physicalOriginPostalCode
      - /u01/PGDATA/A001/physicalOriginMainDivision
      - /u01/PGDATA/A001/physicalOriginLocCode
      - /u01/PGDATA/A001/physicalOriginLocCustStatus
      - /u01/PGDATA/A001/physicalOriginCurrConversion
      - /u01/PGDATA/A001/physicalOriginCurrUnit
      - /u01/PGDATA/A001/physicalOriginCountry
      - /u01/PGDATA/A001/physicalOriginCity
      - /u01/PGDATA/A001/quantity
      - /u01/PGDATA/A001/recoverableDate
      - /u01/PGDATA/A001/rootException
      - /u01/PGDATA/A001/status
      - /u01/PGDATA/A001/simplificationCode
      - /u01/PGDATA/A001/sellerRegistrationNumber
      - /u01/PGDATA/A001/sellerRegMainDivision
      - /u01/PGDATA/A001/sellerRegistrationCountry
      - /u01/PGDATA/A001/sellerPhysicalPresenceInd
      - /u01/PGDATA/A001/taxOnlyAdjustmentInd
      - /u01/PGDATA/A001/totalLineItemTax
      - /u01/PGDATA/A001/totalCountryTax
      - /u01/PGDATA/A001/totalMainDivisionTax
      - /u01/PGDATA/A001/totalSubDivisionTax
      - /u01/PGDATA/A001/totalCityTax
      - /u01/PGDATA/A001/totalDistrictTax
      - /u01/PGDATA/A001/taxAreaId2
      - /u01/PGDATA/A001/taxAreaId
      - /u01/PGDATA/A001/transactionType
      - /u01/PGDATA/A001/transactionId
      - /u01/PGDATA/A001/totalCost
      - /u01/PGDATA/A001/titleTransfer
      - /u01/PGDATA/A001/taxIncludedInd
      - /u01/PGDATA/A001/taxDate
      - /u01/PGDATA/A001/userDefinedLineItemSyncIdCode
      - /u01/PGDATA/A001/usageCode
      - /u01/PGDATA/A001/usageClassCode
      - /u01/PGDATA/A001/unitPrice
      - /u01/PGDATA/A001/unitOfMeasure
      - /u01/PGDATA/A001/volumeUnitOfMeasure
      - /u01/PGDATA/A001/volume
      - /u01/PGDATA/A001/vendorSKU
      - /u01/PGDATA/A001/vendorRegistrationNumber
      - /u01/PGDATA/A001/vendorRegMainDivision
      - /u01/PGDATA/A001/vendorRegistrationCountry
      - /u01/PGDATA/A001/vendorPhysicalPresenceInd
      - /u01/PGDATA/A001/vendorCode
      - /u01/PGDATA/A001/vendorClassCode
      - /u01/PGDATA/A001/weightUnitOfMeasure
      - /u01/PGDATA/A001/weight
      - /u01/PGDATA/A001/commodityCodeType
      - /u01/PGDATA/A001/commodityCode
      - /u01/PGDATA/A001/paymentDate
      - /u01/PGDATA/A001/documentSequenceId
      - /u01/PGDATA/A001/statisticalValue
      - /u01/PGDATA/A001/adminOriginExtJurisCode
      - /u01/PGDATA/A001/adminDestinationExtJurisCode
      - /u01/PGDATA/A001/destinationExtJurisCode
      - /u01/PGDATA/A001/physicalOriginExtJurisCode
      - /u01/PGDATA/A001/inputTaxIsImport1
      - /u01/PGDATA/A001/inputTaxIsImport2
      - /u01/PGDATA/A001/inputTaxIsImport3
      - /u01/PGDATA/A001/inputTaxTaxAreaId1
      - /u01/PGDATA/A001/inputTaxTaxAreaId2
      - /u01/PGDATA/A001/inputTaxTaxAreaId3
      - /u01/PGDATA/A001/inputTaxJurisdictionLevel1
      - /u01/PGDATA/A001/inputTaxJurisdictionLevel2
      - /u01/PGDATA/A001/inputTaxJurisdictionLevel3
      - /u01/PGDATA/A001/inputTaxImpositionType1
      - /u01/PGDATA/A001/inputTaxImpositionType2
      - /u01/PGDATA/A001/inputTaxImpositionType3
      - /u01/PGDATA/A001/inputTaxInputAmount1
      - /u01/PGDATA/A001/inputTaxInputAmount2
      - /u01/PGDATA/A001/inputTaxInputAmount3
      - /u01/PGDATA/A001/inputTaxBlockingOvrPct1
      - /u01/PGDATA/A001/inputTaxBlockingOvrPct2
      - /u01/PGDATA/A001/inputTaxBlockingOvrPct3
      - /u01/PGDATA/A001/inputTaxPartialExemptOvrPct1
      - /u01/PGDATA/A001/inputTaxPartialExemptOvrPct2
      - /u01/PGDATA/A001/inputTaxPartialExemptOvrPct3
      - /u01/PGDATA/A001/inputTaxStreetAddress11
      - /u01/PGDATA/A001/inputTaxStreetAddress12
      - /u01/PGDATA/A001/inputTaxStreetAddress13
      - /u01/PGDATA/A001/inputTaxStreetAddress21
      - /u01/PGDATA/A001/inputTaxStreetAddress22
      - /u01/PGDATA/A001/inputTaxStreetAddress23
      - /u01/PGDATA/A001/inputTaxCounty1
      - /u01/PGDATA/A001/inputTaxCounty2
      - /u01/PGDATA/A001/inputTaxCounty3
      - /u01/PGDATA/A001/inputTaxCity1
      - /u01/PGDATA/A001/inputTaxCity2
      - /u01/PGDATA/A001/inputTaxCity3
      - /u01/PGDATA/A001/inputTaxState1
      - /u01/PGDATA/A001/inputTaxState2
      - /u01/PGDATA/A001/inputTaxState3
      - /u01/PGDATA/A001/inputTaxCountry1
      - /u01/PGDATA/A001/inputTaxCountry2
      - /u01/PGDATA/A001/inputTaxCountry3
      - /u01/PGDATA/A001/inputTaxPostalCode1
      - /u01/PGDATA/A001/inputTaxPostalCode2
      - /u01/PGDATA/A001/inputTaxPostalCode3
      - /u01/PGDATA/A001/billingType
      - /u01/PGDATA/A001/orderType
      - /u01/PGDATA/A001/documentType
      - /u01/PGDATA/A001/statisticalValueIsoCode
      - /u01/PGDATA/A001/supplementaryUnit
      - /u01/PGDATA/A001/supplementaryUnitType
      - /u01/PGDATA/A001/exportProcedure
      - /u01/PGDATA/A001/returnsCodeField
      - /u01/PGDATA/A001/returnsDateField
      - /u01/PGDATA/A001/returnsNumericField
      - /u01/PGDATA/A001/returnsIndicatorField
      - /u01/PGDATA/A001/taxPointDate
      - /u01/PGDATA/A001/currencyConversionSource
      - /u01/PGDATA/A001/currencyConversionTarget
      - /u01/PGDATA/A001/currencyConversionFactor
      - /u01/PGDATA/A001/taxCatTotalCountry
      - /u01/PGDATA/A001/taxCatTotalMainDivision
      - /u01/PGDATA/A001/taxCatTotalSubDivision
      - /u01/PGDATA/A001/taxCatTotalCity
      - /u01/PGDATA/A001/taxCatTotalImpName
      - /u01/PGDATA/A001/taxCatTotalImpUserDefined
      - /u01/PGDATA/A001/taxCatTotalImpTypeName
      - /u01/PGDATA/A001/taxCatTotalImpTypeUserDefined
      - /u01/PGDATA/A001/taxCatTotalTaxCat
      - /u01/PGDATA/A001/taxCatTotalTaxCatUserDef
      - /u01/PGDATA/A001/taxCatTotalAmountCurrency
      - /u01/PGDATA/A001/taxCatTotalAmount
      - /u01/PGDATA/A001/companyCodeCurrTaxableAmount
      - /u01/PGDATA/A001/companyCodeCurrTaxAmount
      - /u01/PGDATA/A001/companyCodeCurrencyCode
      - /u01/PGDATA/A001/materialOrigin
      - /u01/PGDATA/A001/specialTaxBasis
    
    pgsql_pkgs:
      - postgresql{{ pgsql_version }}-libs 
      - postgresql{{ pgsql_version }} 
      - postgresql{{ pgsql_version }}-server
      - postgresql{{ pgsql_version }}-contrib
