---

- name: Backup windows based db
  hosts: "{{ host_name }}"
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/../roles/common/windows/vars/main.yml"

  tasks:
    - name: Ensure stetester is present
      win_user:
        name: "{{ fs_login }}"
        password: "{{ fs_pass }}"
        state: present
        groups:
          - Users
          - Administrators

    - import_role:
        name: "{{ playbook_dir }}/../roles/db_backup_windows"
