# This is the playbook for creating O Series windows install
--- 
- hosts: "{{ host_name }}"
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/../roles/common/windows/vars/main.yml"

  tasks:
  - import_role:
      name: "{{ playbook_dir }}/../roles/vertex_required_windows"
  - import_role:
      name: "{{ playbook_dir }}/../roles/mssql_windows"
