---
# Install Oracle db on Linux host machine.
    - hosts: "{{ host_name }}"
      user: ansible
      become: yes
      connection: ssh
      gather_facts: yes

      tasks:
      - import_role:
          name: "{{ playbook_dir }}/../roles/vertex_required_linux"
      - import_role:
          name: "{{ playbook_dir }}/../roles/oracle_linux"
