# This playbook installs PGSQL, JAVA and O Series 9
---
    - hosts: "{{ host_name }}"
      user: ansible
      become: yes
      connection: ssh
      gather_facts: yes
     
      tasks:
      - import_role:
          name: "{{ playbook_dir }}/../roles/vertex_required_linux"
      - import_role:
          name: "{{ playbook_dir }}/../roles/jdk_linux"
      - import_role:
          name: "{{ playbook_dir }}/../roles/pgsql_linux"
      - import_role:
          name: "{{ playbook_dir }}/../roles/oseries"
