---
- name: Setting ISO Fact 2012
  set_fact:
    mssql_iso_pkg: en_sql_server_2012_standard_edition_x86_x64_dvd_813403.iso
    dotnet_pkg_base_dir: /MS_NET_Framework_3.5_sp1/
    dotnet_pkg: dotnetfx35setup.exe
  when: mssql_version == 2012

- name: Setting ISO Fact 2014
  set_fact:
    mssql_iso_pkg: en_sql_server_2014_standard_edition_x64_dvd_3932034.iso
    dotnet_pkg_base_dir: /MS_NET_Framework_3.5_sp1/
    dotnet_pkg: dotnetfx35setup.exe
  when: mssql_version == 2014
  
- name: Setting ISO Fact 2016
  set_fact:
    mssql_iso_pkg: en_sql_server_2016_standard_with_service_pack_1_x64_dvd_9540929.iso
  when: mssql_version == 2016

- name: Setting ISO Fact 2017
  set_fact:
    mssql_iso_pkg: SW_DVD9_NTRL_SQL_Svr_Standard_Edtn_2017_64Bit_English_OEM_VL_X21-56945.ISO
  when: mssql_version == 2017

- name: Setting Oseries Flag False
  set_fact:
    oseries_flag: false
  when: mssql_db_instance != "oseries"
  
- name: Setting Oseries Flag True
  set_fact:
    oseries_flag: true
  when: mssql_db_instance == "oseries"
